anneal_lr: true
batch_size: 4096
capture_video: false
checkpoint_freq: 10
clip_coef: 0.2
clip_vloss: true
cost_limit: 0.25
cuda: true
ent_coef: 0.0
env_id: f110-multi-agent-v0
evaluation_freq: 10
exp_name: run_ns1024000_climit_20240301
gae_lambda: 0.95
gamma: 0.99
lagrange_mult: 1.0
lagrange_mult_max: 100.0
learning_rate: 0.0003
log_dir: logs/only_adaptive/PPOPID-{f110-multi-agent-v1}/
max_grad_norm: 0.5
minibatch_size: 128
norm_adv: true
norm_cost: true
num_envs: 2
num_eval_episodes: 20
num_minibatches: 32
num_steps: 2048
pid_lagrangian_d_delay: 1
pid_lagrangian_ema_alpha: 0.95
pid_lagrangian_gains:
- 1.0
- 0.1
- 0.1
rpo_alpha: 0.1
seed: 958800
target_kl: null
torch_deterministic: true
total_timesteps: 1024000
update_epochs: 10
use_cbf: true
use_ctrl: true
use_pid_lagrangian: true
verbose: false
vf_coef: 0.5
